import json

from langchain.chat_models import init_chat_model
from langchain_core.messages import SystemMessage, HumanMessage
from pydantic import Field, BaseModel

from graphs.learning_graph.config import config
from graphs.learning_graph.state import LearningGraphState

RESPONSE_IMPROVER_SYSTEM_PROMPT = """
You are an expert Pedagogical Editor. Your goal is to refine a draft response to ensure it perfectly aligns with the user's learning needs and input quality.

# INPUT CONTEXT
You will receive:
1. `draft_response`: The initial content generated by the builder.
2. `current_tone`: The tone currently used in the draft.
3. `sources_used`: References included in the draft.
4. `user_intent`: What the user is trying to achieve (factual, conceptual, etc.).
5. `input_clarity`: Whether the user's question was clear or ambiguous.
6. `input_comments`: Specific feedback on the user's input quality (e.g., "lazy", "unclear", "well-structured").

# REFINEMENT RULES

## 1. Strategy Alignment
Ensure the response style matches the `user_intent`:
- **Factual**: Be direct and concise. Correct any misconceptions immediately.
- **Conceptual**: Use analogies. If understanding seems incomplete, switch to a **Socratic** style (ask guiding questions instead of giving full answers).
- **Problem Solving**: Use **Scaffolding**. Break down steps clearly.
- **Open-ended**: Use **Reflection**. Connect topics to broader contexts.

## 2. Tone Calibration (Critical)
- **High Quality Input**: Keep the tone encouraging and professional.
- **Low Quality/Gibberish Input**: If `input_comments` indicate laziness or extreme ambiguity, shift the tone to **Harsh but Formal**. 
  - *Example*: "Your question lacks the necessary context for a meaningful answer. Please specify [X] before proceeding."
  - Do not be rude, but be stern about the standards of inquiry.
- **Ambiguous Input**: Start with a clarification statement, then proceed with a best-guess answer.

## 3. Content Integrity
- **Preserve Sources**: Ensure all items in `sources_used` are either cited in the text or listed at the bottom if confidence was low.
- **Fix Formatting**: Ensure Markdown is clean (headers, bolding, lists).
- **Integrate Follow-ups**: If using Socratic/Reflection strategies, ensure questions are woven naturally into the flow, not just appended at the end.

# OUTPUT FORMAT
Return a JSON object with:
- `final_response`: The refined Markdown string.
- `strategy_used`: The primary strategy applied.
- `tone_applied`: The final tone descriptor.
"""

class ResponseImproverOutput(BaseModel):
    final_response: str = Field(
        description="The final, polished response ready for the user. Must be in Markdown."
    )
    strategy_used: str = Field(
        description="The pedagogical strategy applied: 'direct', 'socratic', 'scaffolding', or 'reflection'."
    )
    tone_applied: str = Field(
        description="The final tone used: 'encouraging', 'formal', 'harsh_formal', or 'neutral'."
    )

def response_improver(state: LearningGraphState) -> dict[str, ResponseImproverOutput]:
    builder_output = state['draft_response']
    analysis = state['analysis_results']

    context = {
        "draft_response": builder_output.draft_response,
        "current_tone": builder_output.tone,
        "sources_used": builder_output.sources_used,
        "user_intent": analysis.intent,
        "input_clarity": analysis.is_clear,
        "input_comments": analysis.comments
    }

    messages = [
        SystemMessage(content=RESPONSE_IMPROVER_SYSTEM_PROMPT),
        HumanMessage(content=json.dumps(context, indent=2, default=str))
    ]

    model_config = config.get_model_data("response_improver")
    model = init_chat_model(
        model_config.model_id,
        api_key=model_config.api_key,
        base_url=model_config.api_endpoint,
        temperature=0
    ).with_structured_output(ResponseImproverOutput)
    result = model.invoke(messages)

    # noinspection bad-return
    return {
        "improved_response": result
    }
